### ISSUE TITLE
Suggestion: Website (rig.rs) improvements

### ISSUE THREAD

**Issue by qtfkwk** [0xPlaygrounds/rig#105]
1. `cargo install rig-core` is pointless because there is no binary, distracting because its presence suggests one, and produces the error:

    ```text
    error: there is nothing to install in `rig-core v0.4.1`, because it has no binaries
    `cargo install` is only for installing programs, and can't be used with libraries.
    To use a library crate, add it as a dependency to a Cargo project with `cargo add`.
    ```

    Either remove or replace with something actually useful like `cargo add rig-core`.

2. The "Basic LLM" demo currently produces the following error:

    ```text
    error[E0599]: no method named `model` found for struct `rig::providers::openai::Client` in the current scope
     --> src/main.rs:7:22
      |
    9 |     let gpt4 = client.model("gpt4").build();
      |                      ^^^^^ method not found in `Client`
    ```

    Asserting root cause is https://github.com/0xPlaygrounds/rig/commit/0e4e0aeee3d7632d6e88f9c667f5b3ebfc08f933 and https://github.com/0xPlaygrounds/rig/commit/e5e4997a3296d6144766527820f551266b4ec85e (?)

**Comment by qtfkwk** [comment]
3. The [FAQ page](https://rig.rs/faq.html) mentions a `completion_stream` method but there is no mention of it in the GitHub repository (?).

**Comment by mateobelanger** [comment]
Hey @qtfkwk !

Thank you for reporting these mistakes. Much appreciated we'll address them quickly.

**Comment by mateobelanger** [comment]
Fixed with https://github.com/0xPlaygrounds/rig-site/commit/064de1893b1dafe03e29492a74aa91cd538191e9

**Comment by qtfkwk** [comment]
While the rig-site repository isn't public, I can confirm items 1 and 2 are resolved on the https://rig.rs site.

[Item 3](https://github.com/0xPlaygrounds/rig/issues/105#issuecomment-2475191681) is still present though.
