### ISSUE TITLE
Does rig support streaming?

### ISSUE THREAD

**Issue by qtfkwk** [0xPlaygrounds/rig#113]
The [FAQ page](https://rig.rs/faq.html) mentions a `completion_stream` method but there is no mention of it in the GitHub repository (?). 

 _Originally posted by @qtfkwk in [#105](https://github.com/0xPlaygrounds/rig/issues/105#issuecomment-2475191681)_

**Comment by b0xtch** [comment]
Hey I see this was marked as completed but I see no docs on streaming, any idea if this is still an open issue?
