### ISSUE TITLE
feat:  Make OpenAI provider more compatible with third-party APIs

### ISSUE THREAD

**Issue by M4n5ter** [0xPlaygrounds/rig#155]
- [x] I have looked for existing issues (including closed) about this

## Feature Request
Improve OpenAI provider compatibility to better support third-party APIs compatible with OpenAI APIs

### Motivation
- The current default base URL is https://api.openai.com. However, some OpenAI compatible APIs may use different base URLs, such as [xxx.com/v2](https://xxx.com/v2). If we add /v1 at request time, this may cause the request to fail.
- In some cases, tool call messages may be more important than content messages and should be prioritized. Third-party OpenAI compatible APIs may provide both content and tool_calls in the response.

### Proposal
- It is recommended to update the default base URL to a more common format to better accommodate different third-party APIs.
- It is recommended to adjust the order of model matching logic and prioritize tool call messages to ensure timely and correct processing of these messages.

**Comment by 0xMochan** [comment]
Closed by #156
