### ISSUE TITLE
What Does This Have to do With a Token?

### ISSUE THREAD

**Issue by Librechain** [0xPlaygrounds/rig#159]
There’s a cryptocurrency project on Solana called “AI Rig Project” that links itself to your site and git repo. What does this project have to do with that token? What’s the correlation here? Are you all even associated?

**Comment by 0xMochan** [comment]
The same team is involved with both projects, this repo is purely focused on the open source development of the rig library. Please ask in our discord if you have more questions about other projects from the team!
