### ISSUE TITLE
feat: Add support for Anthropic models

### ISSUE THREAD

**Issue by cvauclair** [0xPlaygrounds/rig#3]
## Feature Request
Add Anthropic as a new model provider for Rig.
 
### Motivation
Anthropic (and its model Claude) is a popular model provider that Rig should support. 

### Proposal
Create a new module `rig::providers::anthropic` which should roughly contain the following:
```rust
// src/providers/anthropic.rs
struct Client {
  // TODO
}

struct CompletionRequest {
  // Modeled after Anthropic API
  // TODO
}

impl From<completion::CompletionRequest> for CompletionRequest {
  // TODO
}

struct CompletionResponse {
  // Modeled after Anthropic API
  // TODO
}

impl From<CompletionResponse> for completion::CompletionResponse<CompletionResponse> {
  // TODO
}

struct CompletionModel {
  // TODO
}

impl completion::CompletionModel for CompletionModel {
  // TODO
}
```

Note: Use the existing provider integrations as a guide (see [`rig::providers::openai`](https://github.com/0xPlaygrounds/rig/blob/main/rig-core/src/providers/openai.rs) and [`rig::providers::cohere`](https://github.com/0xPlaygrounds/rig/blob/main/rig-core/src/providers/cohere.rs)).

**Comment by 0xMochan** [comment]
Implemented by #27
