### ISSUE TITLE
feat: Add support for Neo4j vector store

### ISSUE THREAD

**Issue by cvauclair** [0xPlaygrounds/rig#50]
## Vector Store Integration Request
Neo4j is one of the most popular graph databases which also supports vector indices and semantic search. The database comes in two flavors: a community edition and an enterprise edition (both support semantic search). Both edition can be self hosted using the `neo4j` docker [image](https://hub.docker.com/_/neo4j). The database is also available as a fully managed SaaS via [Aura](https://neo4j.com/product/auradb/). 

### Implementation Checklist
- [ ] Create a new companion crate `rig-neo4j` which contains a client struct for Neo4j to perform semantic search
- [ ] Implement the `VectorStoreIndex` trait for the client
- [ ] Write at least one example to demonstrate how neo4j can be used as a vector store in Rig

### Resources
- [Neo4j vector indices](https://neo4j.com/docs/cypher-manual/current/indexes/semantic-indexes/vector-indexes/)
- [Neo4j docker image](https://hub.docker.com/_/neo4j)
- [Neo4j Rust driver](https://github.com/neo4j-labs/neo4rs)

**Comment by mateobelanger** [comment]
@cvauclair It looks like Neo4j has no *pre-filtering* features for Vector Search/Index. Not a dealbreaker but it may be frustrating to use because you can only filter post semantic-search query.
