### ISSUE TITLE
refactor(embeddings builder): update trait

### ISSUE THREAD

**Issue by garance-buricatu** [0xPlaygrounds/rig#88]
* Change `ExtractEmbeddableTrait` to:
```
pub trait Embed {
    fn embed(&self, embedder: &mut Embedder) -> Result<(), EmbedError>;
}

#[derive(Default)]
pub struct Embedder {
    pub texts: Vec<String>,
}

impl Embedder {
    pub fn embed(&mut self, text: String) {
        self.texts.push(text);
    }
}
```

* Update macro accordingly
* On `build()` method, catch errors about exceeding token limit
* Add `rig::to_embed(item: impl Embed) -> Vec<String>` function
* `EmbeddingsBuilder.documents()` must take an iterator

**Comment by cvauclair** [comment]
Closed by #120
