### ISSUE TITLE
bug: VectorStoreIndex top_n function returns embed data

### ISSUE THREAD

**Issue by garance-buricatu** [0xPlaygrounds/rig#99]
- [x] I have looked for existing issues (including closed) about this

`top_n` function returns `Vec<(f64, String, T)>` where `T` is converted to a `serde_json::Value` by the `VectorStoreIndexDyn`.

This becomes a problem because there is no point where the embedding vectors are filtered out of the vector search response.

Then, the agent takes as input this dynamic context and passes all the vectors as part of the context to the provider.

This makes the context window huge = more expensive and way slower.

**Comment by cvauclair** [comment]
Closed by #118 #115
